version: "3.8"
services:
  api:
    build: ./api
    container_name: api_container
    ports:
      - '5000:5000'
      - '8000:8000'
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - mynetwork
  ghostchat:
    build: ./app
    container_name: ghostchat_container
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
      - /app/node_modules
    stdin_open: true
    networks:
      - mynetwork
    depends_on:
      - api
networks:
  mynetwork: